# Global settings for the whole site
[build]
  command = "gulp build" 
  publish = "dist"       

# Local development settings
[dev]
  targetPort = 8888      # The port Netlify Dev will use as a proxy
  publish = "dist"       # Directory to serve files from in local development
