# Global settings for the whole site
[build]
  command = "gulp build" 
  publish = "dist"

[dev]
command = "gulp watch"  # Replace with your specific Gulp command
targetPort = 3000       # Replace with the port your Gulp server uses
